export const ENV_VARIABLES = {
  BACKEND_API_URL: process.env.REACT_APP_BACKEND_API_URL,
  TIMEOUT_REQUEST: process.env.REACT_APP_TIMEOUT_REQUEST,
  ENCRYPTION_MODE: process.env.REACT_APP_ENCRYPTION_MODE,
  ENCRYPTION_KEY: process.env.REACT_APP_ENCRYPTION_KEY,

  FIREBASE_MODE: process.env.REACT_APP_FIREBASE_MODE,
  FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: process.env.REACT_APP_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: process.env.REACT_APP_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
};
