export const ENV_VARIABLES = {
  BACKEND_API_URL: process.env.REACT_APP_BACKEND_API_URL,
  TIMEOUT_REQUEST: process.env.REACT_APP_TIMEOUT_REQUEST,
  ENCRYPTION_MODE: process.env.REACT_APP_ENCRYPTION_MODE,
  ENCRYPTION_KEY: process.env.REACT_APP_ENCRYPTION_KEY,
};
